#env:
#  global:
#  - CC_TEST_REPORTER_ID=d532cc50f9963f0bab07837645f7c9645bdf783927314e28c3bc268becdd51b1

language: node_js
node_js:
- "stable"
addons:
  code_climate:
    repo_token: d532cc50f9963f0bab07837645f7c9645bdf783927314e28c3bc268becdd51b1
script: istanbul cover node_modules/mocha/bin/_mocha -- -R spec
before_script:
- npm install codeclimate-test-reporter istanbul -g
after_script:
- codeclimate-test-reporter < ./coverage/lcov.info
