language: node_js
node_js:
- 13
cache:
  directories:
  - "node_modules"
services:
  - postgresql
before_script:
  - psql -c 'create database "andela-store-manager";' -U postgres

after_success:
- npm run coveralls
