language: node_js
node_js:
- "stable"
cache:
  directories:
  - "node_modules"
services:
  - postgresql
before_script:
  - psql -c 'create database "andela-store-manager";' -U postgres
  - psql "ALTER ROLE postgres WITH PASSWORD 'point_god';"
  - npm run db_migrate
  - npm run db_seed

after_success:
- npm run coveralls